2024-02-09 04:31:04,149 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0dd6f1660>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-02-09 04:31:04,200 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0dd6f3f70>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-02-09 04:31:04,223 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0dd6f0dc0>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-02-09 04:31:08,873 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0df32fee0>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-02-09 04:31:10,773 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0df32ed40>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-02-09 04:31:11,850 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0ddfc27a0>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-02-09 04:31:11,894 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0ddfc0a60>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-02-09 04:31:11,912 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0dd6ab7f0>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-02-09 04:31:11,943 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0df32d450>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-03-13 17:54:41,103 INFO: Luda startup [in /home/egoza/PycharmProjects/LUDAPROJECT/app/__init__.py:71]
2024-06-04 19:02:23,431 INFO: Luda startup [in /home/egoza/PycharmProjects/LUDAPROJECT/app/__init__.py:71]
2024-06-04 19:03:20,241 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x747a79a303d0>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-06-04 19:03:24,968 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x747a788cef20>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-06-04 19:03:26,137 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x747a788cead0>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-06-04 19:03:26,161 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x747a79a58c70>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-06-04 19:03:26,517 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x747a788b3220>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-06-04 19:03:26,865 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x747a788b1690>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-06-04 19:03:27,213 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x747a7889a230>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-06-04 19:03:27,605 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x747a78898310>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
